name: PR Notifications

on:
    pull_request:
        types:
            [
                opened,
                closed,
                reopened,
                edited,
                ready_for_review,
                review_requested,
            ]

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
            - name: Send Discord notification
              uses: Ilshidur/action-discord@master
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK_PR }}
                  content: >
                      ${{
                        if (github.event.action == 'opened') { ':inbox_tray: New Pull Request Opened:' }
                        else if (github.event.action == 'closed') { ':checkered_flag: Pull Request Closed:' }
                        else if (github.event.action == 'reopened') { ':recycle: Pull Request Reopened:' }
                        else if (github.event.action == 'edited') { ':pencil2: Pull Request Edited:' }
                        else if (github.event.action == 'ready_for_review') { ':eyes: Pull Request Ready for Review:' }
                        else if (github.event.action == 'review_requested') { ':bell: Review Requested on Pull Request:' }
                      }}
                      PR: ${{ github.event.pull_request.title }}
                      By: ${{ github.actor }}
