name: Staging Deployments

on:
    push:
        branches:
            - staging

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
            - uses: sarisia/actions-status-discord@v1
              if: always()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK_DEPLOYMENT_STAGING }}
                  title: "Deployment to Staging Environment 🚀"
                  description: "The build has been successfully deployed to the Staging Environment :rocket:. Congratulations, the latest changes are now live! :tada: Let's keep up the good work! :muscle:"
                  color: 0xffa500
