name: Fork Events

on:
    fork:

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
            - uses: sarisia/actions-status-discord@v1
              if: always()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK_FORK }}
                  title: "🔀 New Fork: ${{ github.event.repository.name }}"
                  description: "A new fork of the repository has been created by ${{ github.actor }}: ${{ github.event.repository.html_url }}"
                  color: 0x3399ff
