name: PR Notifications

on:
    pull_request:
        types:
            [
                opened,
                closed,
                reopened,
                edited,
                ready_for_review,
                review_requested,
            ]

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
            - name: Send Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_PR }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "PR ${{ github.event_name }} by ${{ github.actor }}: ${{ github.event.pull_request.title }} - ${{ github.event.pull_request.html_url }}"
