name: Release Notifications

on:
    release:
        types: [published, created, edited, prereleased, released]

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
            - name: Send Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_RELEASE }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "New release: ${{ github.repository }} ${{ github.event.release.tag_name }} ${{ github.event.release.html_url }}"
